{{- if .Values.ingester.enabled }}
{{- $args := dict "ctx" . "component" "ingester" "memberlist" true -}}
{{- $zonesMap := include "mimir.zoneAwareReplicationMap" $args | fromYaml -}}
{{- range $zoneName, $rolloutZone := $zonesMap }}
{{- if $rolloutZone.delayedDownscaleLeader }}
{{- $_ := set $args "rolloutZoneName" $zoneName -}}
apiVersion: rollout-operator.grafana.com/v1
kind: ReplicaTemplate
metadata:
  name: {{ include "mimir.resourceName" $args }}
  labels:
    {{- include "mimir.labels" $args | nindent 4 }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  labelSelector: name=ingester-{{ $zoneName }}
  replicas: {{ $rolloutZone.replicas }}
---
{{- end }}
{{- end }}
{{- end }}
